mkubaczyk/helmsman

helm_helpers.go

Before:
```
NAME                         	REVISION	UPDATED                 	STATUS  	CHART                             	NAMESPACE  
test-ingress                 	3       	Mon Apr 30 13:43:05 2018	DEPLOYED	k8s-ingress-0.1.1                 	kube-systemkube-system
```
When `helm_helpers.go:82` goes to pick up the 10th field, it doesn't exist because it's a part of field 9.  Adding a space ensures the columns don't run together.
After:
```
NAME                         	REVISION	UPDATED                 	STATUS  	CHART                             	NAMESPACE  
test-ingress                 	3       	Mon Apr 30 13:43:05 2018	DEPLOYED	k8s-ingress-0.1.1                 	kube-system kube-system
```

Fix index out of range issue

---

README.md

I have packaged helmsman both the binary releases and the source distributions.

Helmsman is now packaged in archlinux

---

bindata.go
helm_helpers.go

This fixes #61 by changing the `helm_helpers` to use the `json` output from helm instead of relying on the table output, this should also make `helmsman` more resilient to `helm`'s out put changes.

Use helm's json output

---

Makefile
decision_maker.go
dockerfile/dockerfile
init.go
kube_helpers.go
test_files/dockerfile
utils.go

Here's an example output:
```
$ helmsman -f helmsman-common.yaml -f dev/helmsman-dev.yaml
_          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_|version: v1.5.0
A Helm-Charts-as-Code tool.
2018/09/09 13:31:16 INFO: Parsed YAML [[ helmsman-common.yaml ]] successfully and found [ 0 ] apps.
2018/09/09 13:31:16 INFO: Parsed YAML [[ dev/helmsman-dev.yaml ]] successfully and found [ 1 ] apps.
2018/09/09 13:31:16 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ kube-system ].
2018/09/09 13:31:16 INFO: namespace validation -- Tiller is desired to be deployed WITHOUT TLS in namespace [ dev ]. …
```

adding helm diff to the decision maker

---

decision_maker.go
helm_helpers.go
kube_helpers.go

Adding quotes to Helm repo URL and Helm chart version.
This solves #94 and maybe #78 
This is the previous verbose output:
```
2018/09/27 20:49:59 VERBOSE: helm repo add stable https://kubernetes-charts.storage.googleapis.com
2018/09/27 20:50:00 VERBOSE: helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
2018/09/27 20:50:01 VERBOSE: helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
```
This is the new verbose output, you can see the quotes there:
```
2018/09/27 20:50:25 VERBOSE: helm repo add coreos "https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/"
2018/09/27 20:50:25 VERBOSE: helm repo add stable "https://kubernetes-charts.storage.googleapis.com"
2018/09/27 20:50:26 VERBOSE: helm repo add incubator …
```

Adding some quotes

---

README.md

I would like to propose adding ~a `prereqs`~ to the install section in the README.md
Initially I was unaware that I needed more than just `kubectl` and `helm` to use `helmsman`. But it looks like `helmsman` requires the helm diff plugin:
```sh
helm $ helmsman -debug -f helmsman.yaml
_          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.6.2                             
A Helm-Charts-as-Code tool.
2018/10/01 20:08:12 INFO: checking Helm version
2018/10/01 20:08:12 INFO: checking kubectl version
2018/10/01 20:08:12 INFO: validating that kubectl is installed.
2018/10/01 20:08:13 INFO: validating that helm is …
```

Adding to Install section for helmsman

---

docs/desired_state_specification.md
example.toml
example.yaml
kube_helpers.go
release_test.go
state.go
state_test.go

We are required to label namespaces to allow us to use NetworkPolicies. NetworkPolicies only works with namespace selectors and doesn't work with namespace names.

allow labeling namespaces

---

helm_helpers.go

There is a bug where untracked releases are really deleted even if you passed the --dry-run flag to helmsman. This fix ensures that the --dry-run flag is correctly passed along to helm when untracked releases are deleted.

Don't delete untracked releases on a dry-run

---

decision_maker.go
decision_maker_test.go
init.go
main.go
release.go
release_test.go
utils.go

This is an alternative fix for #59. In this fix the relative paths are resolved when the DSF yaml/toml file is loaded, relative to the path that the dsf was loaded from. This aleviates the need to build paths based on pwd in multiple places, and makes it possible to have DSF files in different folders all merge together correctly.

Resolve values and secrets relative to dsf

---

init.go
release.go
state.go
utils.go

Hi,
As a user, when passing multiple DSFs with the `-f` option I expect the values I override in the latter files to be overwritten in the final state, like when passing multiple compose files to `docker-compose`.
This PR addresses that.

Override existing values when merging DSFs

---

decision_maker.go

This fixes execution failures of the `helm diff` subcommand when an app has been defined in the Helmsman state with the `timeout` argument.
Take the example app:
```
[apps]
[apps.grafana]
name = "grafana"
enabled = true
chart = "stable/grafana"
version = "1.17.4"
timeout = 60
wait = true
```
When running `helmsman --show-diff` for the state file, Helmsman will return the following error when trying to run a diff for this app
```
2018/11/19 15:16:36 VERBOSE: helm search stable/grafana --version "1.17.4" -l
2018/11/19 15:16:37 INFO: checking what I need to do for your charts ...
2018/11/19 15:16:37 INFO: mapping the current helm state ...
2018/11/19 15:16:37 VERBOSE: helm list --all --max 0 --output json --tiller-namespace default
2018/11/19 15:16:37 VERBOSE: helm list --all --max 0 …
```

Fix helm diff execution failure when timeout is set for an app

---

decision_maker.go

This change suppresses empty diff. Otherwise it will output new epmpty line for every helm chart.

Suppress empty diff

---

decision_maker.go
docs/how_to/use_local_charts.md
helm_helpers.go
release.go
utils.go

This adds support for charts that are on the file system rather than in a repo. It works by checking
whether a chart has a repo that's listed in the repos section of the DSF. If it doesn't, the chart
name is treated as a file path instead. If the chart is not present on the file system, or the chart
on the file system is a different version than specified in the DSF, validation fails.
This fixes #51.

feat: Support local charts on file system

---

decision_maker.go
helm_helpers.go
plan.go
plan_test.go

Currently all changes are displayed as wall of green text. So sometimes its easy to miss a change when there are a lot of addons. This PR adds colours to changes for visibility. Red for deleting, Blue for adding new addon, Yellow/Orange for change, Green for no change.
Before:
After:

Add colors to decision outputs

---

helm_helpers.go
main.go

clean Tiller certs upon exit when not creating a context. Fixes #168

---

docs/desired_state_specification.md
docs/how_to/define_namespaces.md
kube_helpers.go
namespace.go
release_test.go
state_test.go

Hi there,
I would like a submit a request for allowing annotations to be added to namespaces specify in the helmsman state file. We use kiam to manage AWS roles for our cluster and it involves annotating roles with allowed roles for the resources to assume. This will let us setup those annotation from within helmsman state file instead of needing to maintain a separate files for the namespaces.
This is my first time writing Go so hopefully this is fine. I pretty much copy from the label function since it should work in a similar fashion from Kubernetes' perspective. I also can't find the test files for kube_helpers, so if one does exists, please point me to it and I can write tests for it as well.
Thank you

Add annotation functionality to the namespace

---

bindata.go
data/role.yaml
docs/desired_state_specification.md
kube_helpers.go

this is a follow up to #182 and #187 
We need to keep the new behaviour backward compatible and therefore kube-system without `tillerRole` specified, should by default still get a cluster-admin clusterrole. This can still be overriden by the user if needed with `tillerRole`. This PR addresses this. 
Also this PR fixes the hardcoded custom role name `helmsman-tiller` which now needs to match `tillerRole` when provided. 
Additionally, some minor updates on docs and code comments.

make kube-system default binding to cluster-admin clusterrole

---

docs/desired_state_specification.md
helm_helpers.go
state.go
utils.go

This patch adds support for externally configured helm repositories,
which is a handy tool if you are using Artifcatory as helm repository
server.
In our case, we don't want to push the basic auth credentials to the repositories, but we will make sure that all developers update their helm settings to contain the correct credentials.

Add support for externally configured helm repos

---

aws/aws.go

The AWS SDK is capable of sourcing environment variables from a variety
of sources. The removed check prevents it from doing so for anything but
environment variables.
In particular, we'd like to get EC2 machine roles to work.
This is a possible fix for https://github.com/Praqma/helmsman/issues/207

Remove AWS environment variable check.

---

docs/desired_state_specification.md
docs/how_to/README.md
docs/how_to/namespaces/limits.md
example.toml
example.yaml
kube_helpers.go
namespace.go

There is an outstanding issue in Kubernetes docs about missing Pod type in LimitRange doc - https://github.com/kubernetes/website/issues/9585, so i guess that's why it wasn't added. Although this type exists and we are successfully using it for some time. The proof can be found here for example - https://docs.openshift.com/container-platform/3.11/dev_guide/compute_resources.html#dev-limit-ranges

Dehardcoding LimitRange type to be able to set limits for Pod

---

kube_helpers.go

Add the namespace to clusterrolebindings names.  This way if you use the same service account name for for multiple tiller accounts that are cluster-admins they do not step on each other.
They will follow this naming format `namespace:saName-binding`.

Add namespace to clusterrolebindings

---

docs/how_to/namespaces/labels_and_annotations.md

Typos on word for labels in namespaces labels example

Typo on word labels

---

init.go
plan.go
utils.go

Here I'd like to fix inconsistency of logs' streams. Some of them go to stdout, some to stderr. With this change, only errors go to stderr and other output is directed to stdout.
This allowed me to introduce proper error message trimming when no verbose flag is set. This will resolve an issue, when one runs -dry-run on a chart with yaml syntax, where with error message it exposes all the templated files it created (so potential secrets as well). 
Before (with or without verbose set):
```
2019/04/24 19:32:42 INFO: Executing the plan ... 
2019/04/24 19:32:44 Command returned with exit code: . And error message: Error: YAML parse error on eg-versions-agent/charts/eg-versions-agent/templates/ingress.yaml: error converting YAML to JSON: yaml: line 19: mapping values are not allowed in this …
```

Set proper stdout and stderr streams for logs; trim error message on no verbose

---

README.md
decision_maker.go
docs/how_to/limit-deployment-to-specific-apps.md
init.go
main.go

Since feature requested in #230 would be a significant improvement in our helmsman-based stack, I'd like to propose a `-target` flag which limits an execution to apps defined with such.

Add -target flag to limit execution to specific app

---

init.go
main.go
utils.go

- renamed temp dir from `helmsman-temp-dir` to `.helmsman-tmp`
- defer cleanup of temporary files at the start of main()
- use ioutil TempDir() instead of custom code
There's still one outstanding issue which is that the temp dir won't be
cleaned up properly if the program exits early while if an error happens
inside init().
I had an issue with deployments flapping, and it turned out the cause was a conflict in the temporary directory. This change puts each file into a separate path.

Improve temporary dir handling.

---

docs/cmd_reference.md
init.go
main.go
utils.go

After the environment substitution was fixed in a recent version, we've noticed that it breaks some of the existing official Helm charts by replacing `${random_string}` in Helm values to an empty string. This change introduces a new flag to be able to turn this custom behavior globally for those who are not interested in using environment substitution feature in Helmsman.

Adding global toggle to be able to disable environment substitution

---

decision_maker_test.go
helm_helpers.go

The new  `-target` flag does not ignore untracked releases, even when specifically stating which release we are targeting.
Releases that are not specified by a  `-target` flag is now also ignored.
I have added tests for the `-target` flag behaviour defined in the `decision_maker.go` file, but I am unfortunately not able to write a test for `-target` flag for untracked releases, in the way the code is structured today.
I was thinking that maybe the `func cleanUntrackedReleases()` in `helm_helper` should actually be a part of the `decide(r,s)` func so that all decisions are made when building the plan?

Do not delete untracked releases if the target flag is set.

---

decision_maker.go

diffRelease() expects its flags to end with whitespace, which diffContextFlag does not. This bug prevents the flag from working at all.
A less brittle approach generally would be to pass all flags as separate elements of the Args field, leaving them to be joined by cmd.exec(). This would however result in variable numbers of spaces depending on which flags are enabled.

Fix bug with diff-context flag

---

decision_maker.go
init.go
main.go

This PR fixes #270 by removing the helm `--force` option which has been used by default in helmsman. Now, the `--force` option will be used with helm upgrades only if helmsman's `--force-upgrades` flag is used.

adding --force-upgrades option [ changes default upgrade behaviour]

---

decision_maker.go
helm_helpers.go
init.go
main.go
utils.go

This implements feature requested in #231 
The new `--update-deps` option will cause helmsman to run `helm dep up` on each local chart (defined as a path in the DSF) before the decision process starts.

adding --update-deps option for local charts dependency update before use

---

README.md
docs/how_to/helm_repos/README.md

The docs link to use_private_helm_charts.md under Install -> From Binary in README.md is broken after commit 11787f3d37adf0255650f5506220fed387734311.
I created a new landing README.md under docs/how-to/helm_repos. This contains the same list of how-to of defining helm repos present in docs/how-to/README.md for helm_repos. Also pointed docs link under Install -> From Binary to this new landing page in docs/how-to/helm_repos.
The newly created landing page will look like https://github.com/amaldevs/helmsman/tree/fix-broken-link/docs/how_to/helm_repos. In code the path is hardcoded to https://github.com/Praqma/helmsman/tree/master/docs/how_to/helm_repos to follow the standard followed across README.md file.

Fix for broken link to docs for private helm charts

---

init.go
main.go
utils.go

Add ability to disable environment substitution in values files.
Resolves #280

Add ability to disable environment substitution in values files

---

decision_maker.go

Fixes bug introduced in 'https://github.com/Praqma/helmsman/commit/54d757a2a24ad8e1b18781c64289e9a6e4d56637#diff-4285687681003b9e1299d0581a920915L140'
In `v1.9.1` the following command is generated when installing a chart with `*` as chart version:
```
helm upgrade --install httpbin-default private-repo/default-chart --version "*" --namespace default -f .helmsman-tmp/tmp467875617/dev.yaml --wait --tiller-namespace kube-system --timeout 90 --dry-run --debug
```
Since the above commit, this became:
```
helm install private-repo/default-chart -n httpbin-default --namespace default -f .helmsman-tmp/tmp648299183/dev.yaml --version * --wait --tiller-namespace kube-system --timeout 90 --dry-run --debug
```
The unquoted `*` leads to the following error:
```
Command returned with exit code: . And …
```

Version should be quoted to support *

---

decision_maker.go
helm_helpers.go

This is a crude PR for the issue described in https://github.com/Praqma/helmsman/issues/279
Something I noticed is that `helm search` not only includes exact matches, e.g.:
```
helm search stable/elasticsearch              
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                                 
stable/elasticsearch            1.30.0          6.7.0           Flexible and powerful open source, distributed real-time ...
stable/elasticsearch-curator    2.0.0           5.5.4           A Helm chart for Elasticsearch Curator                      
stable/elasticsearch-exporter   1.7.0           1.0.2           Elasticsearch stats exporter for Prometheus
```
This means that the logic in …

Fetch explicit chart version when deciding to upgrade

---

decision_maker_test.go
helm_helpers.go
helm_helpers_test.go

This PR make sure that when we get the chart version with getChartVersion, we simply return the given release version. Maybe we should read the `Chart.yaml` instead but this is a simple and fast fix.
Also, it adds test for `helm_helpers.go -> getChartVersion` and `decision_maker.go -> inspectUpgradeScenario` in order to make sure that local chart works correctly.
Closes #286

fix: getChartVersion is skipped when local charts

---

docs/desired_state_specification.md
state.go

The feature request #300 with ignored keys in YAML state file, where such keys can be used as YAML anchors to follow DRY rule is really valuable, so I thought of the simplest way to do this. Hence the PR I created with the least change I could do to achieve that.

Add appsTemplates omitempty YAML key to allow YAML anchors in state file

---

decision_maker.go
decision_maker_test.go
helm_helpers.go
kube_helpers.go
plan.go
state.go
utils.go

I was trying to adopt existing DSF file (based on helm 2 with Tiller) to tillerless and found some issues when deleting releases, so decided to fix them.
And I went a bit wider standardising a bit the decision logging. :-)
Also added decisionType ignored for all apps, that were not passed with -target flag, so they are "gray" on plan

Decision logging fixed for tillerless; add decisionType ignored with gray color

---

decision_maker.go
helm_helpers.go

Since helm secrets by default requires tiller to be reachable, `helm secrets dec` command needs to be wrapped with `helm tiller run`

Fix helm secrets dec command when tillerless enabled

---

.gitignore
.goreleaser.yml
command.go
decision_maker.go
decision_maker_test.go
helm_helpers.go
helm_helpers_test.go
init.go
init_test.go
kube_helpers.go
release.go
utils.go

Any execution of a command using bash with the command parameter has been replaced with just the expected command executable (helm and kubectl). And instead of building the arguments as a single string, they are now built using string arrays. This solves the "quoting" problem, that is there when using a single string with all arguments. For example, before this change, a path had to be quoted on Windows to work. By just building string arrays with all the arguments, this problem is solved by Go' os/exec package.
It also solves the problem of using a password protected Helm repo, where the username contains a '$' (for example Harbor creates robot accounts with this). This could be escaped using '$$', but then it still was being interpreted by bash as an environment variable. This could …

Added support of running Helmsman on Windows

---

decision_maker.go
decision_maker_test.go
docs/cmd_reference.md
docs/desired_state_specification.md
docs/how_to/README.md
docs/how_to/misc/limit-deployment-to-specific-group-of-apps.md
helm_helpers.go
helm_helpers_test.go
init.go
main.go
release.go
utils.go

Since `-target` turned out to be quite useful, I'm proposing a variation of it in form of `-group` parameter. Each application can have one group it belongs to and the Helmsman's deployment can be not only limited to specific apps, which in bigger environments led to quite hard to prepare final commands, but also limited to groups of applications.
Thanks to this the control over apps deployment will stay on the same level it is for `-target` but with better visibility.

Add -group flag to limit execution of deployments to specific group of apps

---

aws/aws.go
init.go
main.go
utils.go

This is a new feature implementation to add support for SSM parameter based variables. Both the helmsman state file and any values or secret files are supported. The solution is inspired by a similar feature in serverless-framework. 
With this feature a user can indicate that a particular value should be pulled from an SSM parameter at deploy time of the Helm Chart. 
For example, given a values.yaml file as such: 
```
ingress:
enabled: true
annotations:
kubernetes.io/owner: {{ssm: /environment/owner}}
```
Helmsman will now perform a lookup of the SSM Param value indicated by the SSM param path above and inject the value into the values.yaml file. 
Encrypted SSM Params are also supported by appending `~true` to the SSM Param path. 
For example: 
```
ingress:
enabled: true
annotations: …
```

Adding support for SSM Params in the Helm values files

---

helm_helpers.go
kube_helpers.go

This should fix #336. 
The code could use some more cleaning but I'm trying to keep the changes to the minimum to stay out of the way of @mkubaczyk's HelmV3 PR. I think we should release this before the Helm v3 rewrite so we have a working Helm v2 version.

use the current helm state to identify untracked releases

---

kube_helpers.go

Hi,
This PR annotates namespaces with all annotations at once. It reduces the complexity of the annotation operation from O(n) to O(1).
I noticed that a lot of time was being spent annotating namespaces with one annotation at a time.
Kubectl annotate supports multiple k=v sets at once. This was an easy win I thought.
I've seen a speedup of 56% - but have only tested it sporadically.
Before
```bash
[...SNIP]
$ time helmsman -verbose -f helmsman-deployments.yaml -show-diff -target board -apply
2019/12/13 08:51:25 VERBOSE: kubectl create namespace istio-system
2019/12/13 08:51:27 WARN: I could not create namespace [ istio-system ]. It already exists. I am skipping this.
2019/12/13 08:51:27 VERBOSE: kubectl annotate --overwrite namespace/istio-system …
```

56% speedup in annotating namespaces annotating with all at once.

---

kube_helpers.go

There was a bug in the previous pull request for annotations on namespaces.
- Annotations should be a slice when passed to a command.
- Add same speed-up for creating labels on namespaces.

Annotations should be a slice when passed to a command.

---

examples/example.yaml
internal/app/cli.go
internal/app/helm_helpers.go
internal/app/kube_helpers.go
internal/app/main.go
internal/app/release.go

this PR updates the detection of untracked releases to match helm3 and the recent helmsman rewrites.
The expected behaviour remains the same. If a release is no longer in the desired state file(s) but is deployed in the cluster and labeled as MANAGED-BY=HELMSMAN, then it is considered untracked and should be removed (unless user enables the `--keep-untracked-releases` flag)
@mkubaczyk  I removed the check if the release is targeted before deleting it because it didn't make sense that the release is not in the desired state but is being targeted. Maybe I am missing something?

Fix/untracked releases for helmsman 3.0.0-beta

---

docs/desired_state_specification.md
docs/how_to/misc/merge_desired_state_files.md
examples/example.toml
examples/example.yaml
internal/app/cli.go
internal/app/decision_maker.go
internal/app/decision_maker_test.go
internal/app/helm_helpers.go
internal/app/kube_helpers.go
internal/app/main.go
internal/app/state.go

This PR introduces a `context` stanza in the Desired State File (DSF) to be used as an identity for each DSF allowing Helmsman to distinguish which releases are managed by which DSF.
@mkubaczyk @luisdavim it would be nice if you can have a quick look in case I missed something.
Meanwhile, I will work on updating the docs to release 3.0.0-beta1.

Feature/add context labels to identify different DSFs

---

Gopkg.lock
internal/app/decision_maker.go
internal/app/decision_maker_test.go
internal/app/helm_helpers.go
internal/app/helm_helpers_test.go
internal/app/main.go

Since plan (aka. diffing) is on a second place of time execution right after charts installation/upgrade, I'm adding goroutines to diffing and checking charts availability to improve this part a bit.
Fixed tests and checked that locally, but I'd like someone else to confirm it's ok before it lands in master.

Add goroutines-based parallel execution of plan and charts availability checking

---

internal/app/decision_maker.go
internal/app/release.go
internal/app/state.go

My previous PR ( #353 ) changed the behaviour around cleaning untracked releases, I think it's safer to keep the previous behaviour where we only consider untracked releases for the namespaces being managed by the current desired state, many people I know use per namespace desired states, this would force them to start using the new context feature but migration could be tricky.

Don't remove untracked releasees from namespaces not tracked by the current desired state

---

internal/app/release.go

I think this is the fix for the issue mentioned below, unsure if this is dirty or not.
I'm not too sure why we are not parsing it as YAML?
https://github.com/Praqma/helmsman/issues/362

Fix for matching wrong version on local charts

---

docs/cmd_reference.md
internal/app/cli.go
internal/app/release.go
internal/app/utils.go
release-notes.md

This PR deprecates some cmd flags that were enabled by default in v3.0.0-betaX and replaces them with options to do the opposite behaviour.
Namely, the deprecated flags are:
```
--suppress-diff-secrets (no opposite behaviour flag introduced since it's unlikely to be used)
--no-env-values-subst
--no-ssm-values-subst
```
The introduced flags are:
```
--subst-env-values
--subst-ssm-values
```

deprecate some cmd flags

---

internal/app/helm_time.go

Fixes #392 
It just adds backup parse layout until helm updated date issue is explained or fixed (whatever is right).

Add backup helmTime parse layout with doubled timezone offset

---

internal/app/decision_maker.go
internal/app/helm_release.go
internal/app/kube_helpers.go
internal/app/main.go
internal/app/release.go
internal/app/release_test.go
internal/app/state.go

This should shorten time needed for targeted deployments as it does not waste time for checking namespaces, charts availability and current state of releases not included in -target flag.

Enhance target flag to ignore all releases states not targeted 

---

internal/app/decision_maker_test.go
internal/app/helm_helpers.go
internal/app/main.go
internal/app/release.go
internal/app/state.go

I'm taking advantage of -target limited actions flow merged with #405
When this is merged, I'd like to release 3.1.0, because latest commits introduced some significant enhancements with targets/groups and helm repos

Reuse -target flag flow for -group passed

---

internal/app/release.go

Helmsman fails on missing helm-secrets plugin even though hiera-eyaml based secrets are used.

Disable checking helm-secrets plugin installed when hiera-eyaml used for secrets

---

internal/app/helm_helpers.go

Hello :)
This is a fix proposal for issue #400 
Chart name in DSF file can be a chart from a repository, a path to a local directory or a TGZ archive.
DSF file is currently not idempotent when using a path to a TGZ archive or a path to a local directory where the directory name is different from the chart name because it rely on a regex on the chart name field to get the chart name.
When the chart name is a path to a TGZ archive, the extracted chart name will always be wrong. When it's a local directory, the chart name will be wrong if the directory name is differont from the chart name defined in Chart.yaml.
This PR is a proposal to fix these two issues by executing "helm show chart" and getting chart name from the command output instead of using a regex on the provided chart name in DSF …

Fix proposal for issue #400

---

internal/app/namespace.go

defining namespace limits in a toml formatted DSF fails due to the `type` being lost in marshalling/unmarshalling. This PR fixes this issue.

fix namespace limits from toml dsf

---

internal/app/cli.go
internal/app/decision_maker.go

On large deployments (> 200 releases) the buildState function can be quite long due to a lot of calls to getReleaseContext.
This workaround drastically reduces the buildState time by allowing to bypass the getReleaseContext by assigning a user provided context to every releases.
This is a workaround that can only be used in some specific situations where we know that there would not be any conflicts between contexts.

Override getContext operation for faster deployments

---

docs/cmd_reference.md
docs/desired_state_specification.md
docs/how_to/README.md
docs/how_to/apps/migrate_contexts.md
docs/how_to/misc/merge_desired_state_files.md
docs/how_to/misc/migrate_to_3.md
internal/app/cli.go
internal/app/decision_maker.go
internal/app/helm_release.go
internal/app/main.go
internal/app/state.go

This PR fixes #413 .
It provides two features with one added flag; `--migrate-context`. This flag updates the context labels on the helm releases secrets/configmaps to use whatever context name you have in the DSF.
Additionally, the same flag can be used after migration of helm2 releases to helm3. The 2to3 plugin does not migrate Helmsman labels, thus helmsman can't continue to manage the same releases after they have been migrated. By using the `--migrate-context` flag once, helmsman can recognize those releases again.  
The flag can be used in combination with any other flags and is safe to run multiple times.

support overriding helmsman contexts and enable smooth migration of helm 2 to 3  

---

docs/how_to/README.md
docs/how_to/namespaces/quotas.md
examples/example.toml
internal/app/kube_helpers.go
internal/app/namespace.go
internal/app/release_test.go
internal/app/state_test.go

refactored version of this https://github.com/Praqma/helmsman/pull/340, we're going to use helm3 and helmsman3 so don't need tiller resources so just resource quotas

add resource quotas

---

helm_helpers.go

`helm init --force-upgrade` does not work without `--upgrade` option.

Use --upgrade instead of --force-upgrade with helm init

---

utils.go

If a call to `notifySlack` passes a string with double quotes in the `content` argument then the webhook fails silently and returns false.
This is because Slack Webhook returns HTTP 400, "invalid_content" due to invalid JSON syntax in the POST request.
Before the fix:
If the `content` was e.g.: `... some text "other text" more text ...`, then the Slack Webhook payload would render an invalid JSON:
```
{
"attachments": [
{
...
"title": "... some text "other text" more text ...",
...
}
]
}
```
After the fix:
Slack payload for the same `content` would render a valid JSON:
```
{
"attachments": [
{
...
"title": "... some text \"other text\" more text ...",
...
}
]
}

Fix JSON quoting issues in Slack notifications

---

plan.go

this pr is just a small attempt to make the plan colors a little easier to read. heres a preview:
im color blind, so maybe its just me, but  this is way better to pick out the changes/deletions etc from the noops.
thx to @oedmarap for helping me with the colors.

make plan colors a little better on the eyes

---

scripts/setup.sh

`gnupg` is missing from the helmsman docker image, but it is a dependency for `helm-secrets`.
This PR includes `gnupg` in the list of packages installed during the Docker build.
This solves https://github.com/Praqma/helmsman/issues/448
Signed-off-by: Mehdi Yedes <mehdi.yedes@gmail.com>

Add gnupg to Docker image

---

docs/desired_state_specification.md
internal/app/release.go

As mentioned in https://github.com/Praqma/helmsman/issues/332, I have tried using the `helmFlags` option to add the `--set-file` flag to the Helm install command without success.
So I have created this PR in an attempt to address that issue and add the `setFile` to the list of the available options.
The TOML stanza would be:
```
[apps.<app_name>.setFile]
```
Tested it locally with the built `helmsman` binary and it worked fine.
Signed-off-by: Mehdi Yedes <mehdi.yedes@gmail.com>

Support the Helm --set-file flag

---

docs/desired_state_specification.md
internal/app/release.go

- Use helm upgrade --install for both helm install and upgrade calls.
- Ensure that helmFlags are passed to both install and upgrade calls and that the same args are passed.
- Split diff arguments to return only helm diff compatible flags. `helmFlags` are not passed to helm diff calls. 
- Update docs to recommend not using `helmFlags` for setting values and to use `set`, `setString` or `setFile` options in the desired state file instead.

fix inconsistent helm args between install and upgrade. fixes #451

---

docs/desired_state_specification.md
docs/how_to/apps/multiple_values_files.md
internal/app/utils.go

- Allow absolute paths to be used for values/secrets/etc files.

allow absolute paths for values/secrets/etc files. Fixes #437

---

internal/app/decision_maker.go
internal/app/helm_release.go

When releases are in `pending-install/rollback` or `uninstalling`, Helmsman aborts execution correctly, but the error message reported is far from accurate:
```
CRITICAL: Release [ test ] in namespace [ test ] already exists but is not managed by the current context: [ test-context ]. Applying changes will likely cause conflicts. Change the release name or namespace.
```
This PR catches those statuses and report an appropriate error message.

report the right error message for releases that are in pending state

---

docs/how_to/apps/lifecycle_hooks.md

Fixing a small typo in the lifecycle hooks docs.
Signed-off-by: Mehdi Yedes <mehdi.yedes@gmail.com>

Fix typo in docs

---

internal/app/utils.go

Fixes #469 
Use the TempFile function to avoid name conflicts in copied files in the temporary directory.
In 3.4.0, with a values file in folderX/values.yaml, helmsman generates a temporary file in .helmsman-tmp/tmp123456789/values.yaml, overwriting any other values.yaml file already copied there.
This PR randomizes the name of the temporary file: .helmsman-tmp/tmp123456789/520934115values.yaml, resolving the conflict.

randomize temporary file names

---

internal/app/utils.go

don't validate env vars when files don't contain `$`

don't validate env vars when files don't contain dollar signs

---

Dockerfile
internal/app/decision_maker.go
internal/app/decision_maker_test.go
internal/app/helm_helpers.go
internal/app/main.go
internal/app/release.go
internal/app/release_test.go

In short, this PR makes `helmsman` call `helm` less. 
If we have 100 apps, and they are all on the same version of the same chart, helmsman would validate that chart 100 times in a row with identical calls to `helm`. This doesn't need to happen. I kept the idea of running helm commands concurrently a `resourcePool` number of times (more on `resourcePool` vs the `-p` flag later in this comment), but I have expanded it -- we concurrently ask helm about the charts (like we used to), but we only do so once per chart version pair (at least in `makePlan`). 
Compared to my previous PR, I am no longer trying to cache chart names and versions in an atomic `sync.Cache`. Since we went to the OS and called helm a bunch of times concurrently, they'd all check the cache and see the result wasn't there, …

Performance improvements

---

internal/app/logging.go

Fixes #473 
With this fix we get the critical message when a variable is not defined instead of the segmentation fault:
```
2020-05-19 09:59:13 INFO: validating environment variables in /Users/ndegory/Git/src/REDACTED/tmp945558632/884846247values.yaml
2020-05-19 09:59:13 CRITICAL: $REGION is used as an env variable but is currently unset. Either set it or escape it like so: $$REGION
```
Added an interface so that this kind of issues can be seen at compilation time.

Add the Critical(string) function to Logger

---

internal/app/release.go

To be honest I don't know why the helm tests were only considered for install action. :-)

Run helm tests also when upgrading chart

---

internal/app/plan.go

Should fix #490 
This also fixes another issue when failing hooks for a chart were not failing its deployment and their results were just ignored
For the sake of readiness I let myself repeate some IFs in releaseWithHooks function

Fix missing valid parallel run for cmd exec after hooks were introduced

---

Dockerfile

Fixes https://github.com/Praqma/helmsman/issues/500
This makes sure that `gnupg` and `sops` are available in the final docker image.
Signed-off-by: Mehdi Yedes <mehdi.yedes@gmail.com>

Add gnupg and sops to the final Docker image

---

internal/app/helm_helpers.go

Since helmsman is calling `helm repo add` with `--username` and `--password`, this removes the duplicate username and password inline with the repository URL.

helmRepos: remove "user:pass@" from url when adding repo

---

Makefile
docs/desired_state_specification.md
internal/app/plan.go
internal/app/release.go
internal/app/release_test.go
tests/overlay.sample.yaml
tests/post-renderer.sh

This PR implement the post renderer Helm feature as a first class citizen option in the Helmsman DSF app config.
It was already possible to use the post renderer via the HelmFlags array, as mentioned in #414 , this implementation adds:
- validation that the path of the executable is valid
- pass the post renderer option to helm diff
Signed-off-by: Nicolas Degory <ndegory@gmail.com>

post-renderer option

---

Makefile
internal/app/plan.go

After https://github.com/Praqma/helmsman/pull/521 the tests are actually executed and that seems to reset all the Helmsman labels in the helm release so I'm moving the labelling function to be executed after that.
Signed-off-by: Luis Davim <luis.davim@jet.com>

fix: helm test resets release labels

---

internal/app/cli.go
internal/app/release.go
internal/app/state.go

A missing app.Name in the DSF would only default to the app state key when the state was validated. The `--skip-validation` flag would fallback to empty names, which unintendedly attempts to delete and install the release:
```
2020-10-09 09:13:23 NOTICE: Release [  ] version [ x.y.z ] will be installed in [ mynamespace ] namespace -- priority: -1000
2020-10-09 09:13:23 WARNING: Untracked release [ myapp ] found and it will be deleted -- priority: -1000
```

fix: handle default app name even when --skip-validation is used

---

internal/app/helm_helpers.go

Fix #530  and #512 
Add the `--devel` option to the `helm show chart` command. This makes it work with chart that only have pre releases (X.Y.Z-pre.something), and still works with the normal use case.

extractChartName works even when only dev versions are published

---

docs/cmd_reference.md
internal/app/cli.go
internal/app/decision_maker.go

Add flag to run an upgrade even if helm diff finds no changes, allowing to overwrite manual changes made to the cluster (works around the missing 3-way diff in the helm-diff plugin as described in #487 )

Add --always-upgrade flag

---

README.md

Hi,
thanks for your work.
In the quick install section, there are some `\` before `_` which is incorrect.
Here is a small fix.
Regards

Fix donwload location

---

internal/app/cli.go
internal/app/command.go
internal/app/decision_maker.go
internal/app/helm_release.go
internal/app/kube_helpers.go
internal/app/main.go
internal/app/plan.go
internal/app/utils.go

I hope this will mitigate the problems from #539
I've added retryExec to run `Getting Helmsman-managed releases` and `Listing all existing releases` with retries. It won't affect anyone not experiencing the same issues, but for those that do (like https://github.com/helm/helm/issues/7997) it should at least do its best. 
In the next iteration we can implement exponential backoff instead of waiting fixed time as it is now, but first I'd like to release this change and collect some examples.

Add retryExec func for getting cluster status methods

---

internal/app/release.go

I forgot to wrap helm diff command with retryExec.
I'd also like to release it as 3.5.1 if possible.

Add retryExec to diff()

---

internal/app/decision_maker.go
internal/app/helm_helpers.go

also add '--skip-refresh' flag as 'helm repo update' is already run by helmsman, and is otherwise not safe to use in parallel

-update-deps: run "helm dep up" concurrently

---

internal/app/release.go
internal/app/release_files.go
internal/app/state_files.go

A first cut of shell hooks was released in https://github.com/Praqma/helmsman/pull/546 -- looks like there's a bug in how `isValidFile` is being used for hooks. I think it should be a `==` instead of `!=` in a few of these places.
**Repro**
DSF:
```
<snip>
apps:
sample:
name: sample
valuesFiles:
- sample-values.yaml
<snip>
hooks:
postInstall: my-legit-command-here
```
Error:
```
...
2020-11-23 22:18:07 INFO: sample-values.yaml will be used from local file system.
2020-11-23 22:18:07 INFO: cluster-meta.yaml will be used from local file system.
2020-11-23 22:18:07 CRITICAL: open : no such file or directory
```
This is definitely a hotfix, though. Leaving as WIP while I continue to validate and open to suggestions of more durable solutions here.
cc @luisdavim

fix: isValidFile error for hooks should not lead to a file resolve.

---

internal/app/release.go

Helm tests currently modify their Helm releases, clobbering any labels / annotations. This has previously caused problems with Helmsman's labelling, and will also cause problems if a shell post-hook does anything with those release secrets.
As such, we should run Helm tests first thing, immediately after the release is installed / upgraded.

feat: Helm test command should run first after the release is installed.

---

internal/app/plan.go

Shell hooks potentially have helpful `stdout` contents that we'd want to optionally (verbose only) see in an error scenario.

feat: commands should optionally log stdout on failures.

---

internal/app/release.go

Since helm diff is run parallelly for multiple releases, sometimes it's impossible to distinguish which release the critical error is referring to, e.g.
```
2020-12-01 13:45:32 INFO: Diffing release [ a ] in namespace [ n ]
2020-12-01 13:45:32 INFO: Diffing release [ b ] in namespace [ n ]
2020-12-01 13:45:32 INFO: Diffing release [ c ] in namespace [ n ]
2020-12-01 13:45:32 INFO: Diffing release [ d ] in namespace [ n ]
2020-12-01 13:45:34 CRITICAL: Command returned with exit code: 1. And error message: Error:
Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: 
error validating "": error validating data: ValidationError(Deployment.spec): unknown field "updateStrategy" 
in io.k8s.api.apps.v1.DeploymentSpec
Error: plugin "diff" exited …
```

Clarify diff error message

---

internal/app/utils.go

This fixes segmentation fault in notifySlack, when there was an error from http.Client and response was nil.
```
2020-11-30 18:25:07 INFO: Posting notifications to Slack ...
2020/11/30 18:25:08 protocol error: received *http.http2GoAwayFrame before a SETTINGS frame
2020-11-30 18:25:08 INFO: Cleaning up sensitive and temp files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcc2939]
goroutine 1 [running]:
github.com/Praqma/helmsman/internal/app.notifySlack(0xc0004bc280, 0x4c, 0xc0000ae1e0, 0x4f, 0xc0004b0000, 0x0)
/go/src/github.com/Praqma/helmsman/internal/app/utils.go:548 +0x6f9
github.com/Praqma/helmsman/internal/app.(*plan).sendToSlack(0xc0005080a0) …
```

Fix notifySlack segmentation fault

---

internal/app/release.go

This reverts the change from #560, turns out I tested it on older version of helmsman when cmd.Exec was used instead of cmd.RetryExec for `helm diff`. Now it looks like this clarification was redundant:
```
2020-12-10 11:21:28 ERROR: Diff for release [x] in namespace [y] returned with exit code: 1.
And error message: After 3 attempts of Diffing release [ x ] in namespace [ y ], it failed with:
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from
release manifest: error validating "": error validating data: ValidationError(Deployment.spec):
unknown field "updateStrategy" in io.k8s.api.apps.v1.DeploymentSpec
```
@mkubaczyk Sorry for this confusion

Revert Clarify diff error message

---

internal/app/release_files.go

Hey folks 👋 
I'm using [helm-secrets](https://github.com/jkroepke/helm-secrets) with the [vault driver](https://github.com/jkroepke/helm-secrets#change-secret-driver) and I'm facing that issue:
```
HELM_SECRETS_DRIVER=vault helmsman -f state_v3.toml -target foo -show-diff -debug
_          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v3.6.3
A Helm-Charts-as-Code tool.
2021-01-19 23:35:05 DEBUG: helm version --short -c
2021-01-19 23:35:05 DEBUG: helm version --short -c
2021-01-19 23:35:05 DEBUG: kubectl version --client --short
2021-01-19 23:35:05 DEBUG: helm plugin list
2021-01-19 23:35:05 INFO: Parsed …
```

fix: side-effect on r.SecretsFiles when having multiple successive call

---

internal/app/release.go

fix: skip helm tests in dry-run mode

---

internal/app/command.go
internal/app/command_test.go
internal/app/decision_maker.go
internal/app/helm_helpers.go
internal/app/helm_release.go
internal/app/kube_helpers.go
internal/app/plan.go
internal/app/release.go
internal/app/release_files.go
internal/app/state.go
internal/app/state_test.go
internal/app/utils.go

Per https://github.com/Praqma/helmsman/issues/598
But I ran into something that should probably be fixed first: https://github.com/Praqma/helmsman/pull/600
Based on this and that, I won't be looking to merge this until I add some (locally-passing!) tests. In particular the constant parsing of `ExitStatus.output` is a bit worrisome and merits some more tests (I saw some JSON unmarshaling!). I don't think the error exit status is parsed.

feat: command.Exec() returns (*ExitStatus, error) enabling more idiomatic error management.

---

internal/app/kube_helpers.go
internal/app/utils.go

I've been encountering issues locally running helmsman that I think are a result of a failed copy of local files.
The files are first copied from once from the location defined in `certificates: { caCert: "/path/to/ca.crt" }` to a temporary location, and then again from the temporary location to the current directory at `ca.crt`. the latter copy creates a file of 0 bytes in size, causing `kubectl` commands to fail. This either means `to.Close()` is returning an error (this error is ignored by the code) or `io.Copy()` is copying 0 bytes. I was going to add some debug logging to `copyFile`, but I realized that it probably doesn't make sense to "download" a local file in the first place. In running some tests, the local files are "downloaded" (copied) at least twice for no discernible …

do not "download" local files

---

internal/app/command.go

We should optimistically always return stdout/stderr when we `cmd.Exec()`, even if the err isn't an `*exec.ExitError`.

fix: include stdout and stderr in all Exec returns.

---

docs/deployment_strategies.md
docs/how_to/apps/order.md
docs/how_to/apps/override_namespaces.md
docs/how_to/misc/limit-deployment-to-specific-apps.md
docs/how_to/misc/limit-deployment-to-specific-group-of-apps.md
examples/appsTemplates/apps/puppetserver/common-values.yaml
examples/appsTemplates/config/helmsman.yaml
examples/example.toml
examples/example.yaml
examples/job.yaml
examples/minimal-example.toml
examples/minimal-example.yaml
internal/app/cli.go
internal/app/state_files.go
internal/app/state_files_test.go
tests/invalid_example.toml
tests/invalid_example.yaml

Should also fix: https://github.com/Praqma/helmsman/issues/582

Chart urls and repos

---

internal/app/cli.go
internal/app/helm_helpers.go
internal/app/kube_helpers.go
internal/app/utils.go

fix: --server-dry-run was deprecated in kubectl 1.18

---

internal/app/helm_helpers.go
internal/app/kube_helpers.go

fix: checkKubectlVersion doesn't work with trailing spaces in the version number

---

internal/app/command.go
internal/app/command_test.go

When printing kubectl commands for debug logs, redact the --token and
--password arguments so that it doesn't leak credentials into logs.

feat: redact --token and --password arguments

---

docs/desired_state_specification.md
internal/app/decision_maker.go
internal/app/decision_maker_test.go
internal/app/state.go

Adding `skipIgnoredApps` option in Settings block of DSF file.
When defined as `true`, output plan will be limited to the apps with decision different than `ignored`. This will help in multiple helmsman runs when `-target` or `-group` flag is used on DSF having significant number of apps causing the plan to contain tons of `ignored` lines making the plan hard to read.
What do you think?

Add skipIgnoredApps option to DSF Settings block

---

docs/how_to/apps/basic.md

Links were incorrect and getting 404s for `example.yaml` and `example.toml`.  Looks like they might have moved at some point.

Fix broken links in examples

---

internal/app/cli.go
internal/app/command.go
internal/app/decision_maker_test.go
internal/app/helm_helpers_test.go
internal/app/kube_helpers.go
internal/app/release.go
internal/app/spec_state_test.go
internal/app/state_files_test.go
internal/app/state_test.go

`kubectl diff` returns 1 when there's a diff and the command was always being retried, this should fix it and it also adds some missing error checks.

Diff exit code

---

docs/cmd_reference.md
internal/app/cli.go
internal/app/main.go
internal/app/release.go

Hi!
Here's a small feature for running a check for available updates for charts used in the states apps.
It's often easier to keep up with the chart updates when moving in smaller steps, but keeping up on what could be updated is an annoying chore. This feature helps a bit with the tracking.

Option for checking for available updates for app charts

---

Makefile

This PR updates the cross compilation task to add support for Linux/MacOS arm64 builds.
With this PR the following builds are created:
```
% make cross
Number of parallel builds: 9
-->    darwin/amd64: github.com/Praqma/helmsman/cmd/helmsman
-->     linux/arm64: github.com/Praqma/helmsman/cmd/helmsman
-->   windows/amd64: github.com/Praqma/helmsman/cmd/helmsman
-->    darwin/arm64: github.com/Praqma/helmsman/cmd/helmsman
-->     linux/amd64: github.com/Praqma/helmsman/cmd/helmsman
```

Support arm64 builds

---

.goreleaser.yml

This change is a follow up to previously merged PR #642 and ensures arm64 builds will be published when running `make release`.
I tested running `make cross` and `make release` successfully on my own fork - see https://github.com/mixja/helmsman/releases.

Add arm64 arch option to goreleaser

---

docs/cmd_reference.md
internal/app/cli.go

This solves #645 and makes the loading of `.env` files behave as I would expect them to but it does change the existing behaviour quite significantly:
* Before the default `.env` file would only be loaded if no env files were explicitly passed through the `-e` flag, now it will always be loaded first if present
* Before loading env files would not overwrite any env variable that had already been set before, now it does so when loading multiple files if a variable is set more than once the value from the last file to be loaded will take precedence.
* Before the first file would take precedence, now, the last one will.
I've checked the documentation and there's no mention to what is the expected behaviour.
I think this behaviour is more natural and intuitive but what do you think @mkubaczyk

fix: .env files should overwrite env vars

---

internal/app/cli.go
internal/app/state_files.go
internal/app/utils.go
internal/app/utils_test.go

feat: recursively expad env variables

---

docs/cmd_reference.md
docs/how_to/README.md
docs/how_to/misc/exclude-apps-or-groups-from-deployment.md
internal/app/cli.go
internal/app/decision_maker_test.go
internal/app/state.go
internal/app/state_test.go

This PR adds `-exclude-target` and `-exclude-group` CLI flags so one can exclude specific apps by either their names or groups from execution no matter if `-target` and `-group` flags were used or not. This came useful for me when trying to redeploy whole environment without one or two apps that I had to take care differently.
It works for every possible case as I'm disabling those apps on an early stage even before considering `-target` or `-group` flags.

Add -exclude-target and -exclude-group cli options

---

internal/app/cli.go

I noticed that an invalid application configuration didn't error out when creating a plan. Instead it would just exit and say that no applications were found. Specifically, I had `preInstall` under the application instead of under `my-app.hooks`. Digging in, it appears that errors from parsing were being returned, but the `build` method on the state wasn't handling the error being return. This simply handles the error and returns it so that it is correctly outputted to the screen so the issue is shown to the user instead of being swallowed.

Add error handling to state building from files

---

docs/cmd_reference.md
internal/app/cli.go
internal/app/main.go

Feature request - #527
The PR adds a new flag `detailed-exit-code` that makes the CLI return more granular exit code based on a execution plan. The feature is useful for building some CI logic on top of it.
I tested the feature locally:
```
> ./helmsman -show-diff -detailed-exit-code -no-fancy -f examples/minimal-example.yaml
2022-06-03 23:18:55 NOTICE: -------- PLAN starts here --------------
2022-06-03 23:18:55 NOTICE: Release [ jenkins ] in namespace [ staging ] will be installed using version [ 2.15.1 ] -- priority: 0
2022-06-03 23:18:55 NOTICE: Release [ artifactory ] in namespace [ staging ] will be installed using version [ 11.4.2 ] -- priority: 0
2022-06-03 23:18:55 NOTICE: -------- PLAN ends here --------------
> echo $?
2
```
```
> ./helmsman -show-diff -no-fancy -f …
```

Add detailed exit code feature

---

go.mod
go.sum
internal/app/helm_helpers.go
internal/app/kube_helpers.go
internal/app/namespace.go
internal/app/release.go
internal/app/spec_state.go
internal/app/state.go
internal/app/state_files.go
schema.json

Since https://github.com/invopop/jsonschema/pull/23 was merged `jsonschema` no longer supports `yaml` tags,  and we've updated to that version in https://github.com/Praqma/helmsman/pull/682,  we'd need to add addition json tags to keep using go-yaml, we can avoid duplicate YAML and JSON tags by using `sigs.k8s.io/yaml` that first converts YAML to JSON using go-yaml and then uses `json.Marshal` and `json.Unmarshal` to convert to or from the struct. This means that it effectively reuses the JSON struct tags as well as the custom JSON methods `MarshalJSON` and `UnmarshalJSON` unlike go-yaml.

refactor: use sigs.k8s.io/yaml and json tags

---

internal/app/logging.go
internal/app/utils.go

- use `log.Fatal()` if there is a environment variables substitution validation error in values file instead of `log.Critical()`
- use `log.Fatal()` if there is an error while reading a values file
- remove `Critical` method from `Logger` as unused function
When Helmsman validates values files and one of the environment variables is unset, it writes a log message with a critical level to the stdout, **but** doesn't interrupt execution. This behavior seems unintended, and might lead to situation when a misconfigured chart gets installed into a k8s cluster.
Given:
**charts/charts.yaml**
```yaml
helmRepos:
jenkins: https://charts.jenkins.io
namespaces:
staging:
apps:
jenkins:
namespace: staging
enabled: true
chart: jenkins/jenkins
version: 2.15.1
valuesFile: ./jenkins.yaml
``` …

exit when env variables substitution fails

---

internal/app/helm_helpers.go
internal/app/utils.go

Based on #721, but use stdout of helm-secrets directly, like in eyaml. Should fix #715.
- fix: check helm plugin version
- fix: use helm-secrets stdout on newer versions

helm-secrets 4

---

internal/app/helm_helpers.go
internal/app/release.go

feat: allow setting the version to latest

---

docs/how_to/helm_repos/gcs.md
docs/how_to/misc/auth_to_storage_providers.md
internal/gcs/gcs.go

Currently helmsman requires certificate provided via GOOGLE_APPLICATION_CREDENTIALS or GCLOUD_CREDENTIALS environment variable to read charts from GCP.
When running inside GCP helmsman can use metadata server to authenticate as Service Account.
This change prevents helmsman from failing when no env variables are provided, but metadata server is available.

allow use of metadata server for gcs authentication inside GCP

---

internal/app/utils.go

Fixes #758 
- `helm-vault` does not support outputting secrets to stdout, so `useHelmOutput` is set to `false`
- `helm-vault` interpolates the environment variable name into the output file if one is specified, so an additional step of renaming the file to the expected name is added
- `helm-vault` outputs the expected file by default (original file name with `.dec` appended) if no environment is specified. No changes required to handle this case other than settings `useHelmOutput` to `false`

Fix helm-vault secret decryption

---

Dockerfile
internal/app/state.go
internal/app/utils.go
schema.json

I have noticed, that helmsman supports `hiera-eyaml` with only local PKCS7 keys for secrets. This PR adds support for Google Cloud KMS in `hiera-eyaml`.
Currently, helmsman only supports `hiera-eyaml` with local PKCS7 keys for secrets. This limits users who want to manage their keys differently.
I have made a code changes to add support for `hiera-eyaml-gkms`, which is a plugin for `hiera-eyaml `that extends default `hiera-eyaml` functionalities. This will allow users to encrypt and decrypt secrets using GKMS keys stored in GCP. Users can specify the project id, keyring and crypto-key they are referring to.
These change will add a valuable feature to helmsman allowing users to use different method and can be a starting point to include also different cloud providers for `heira-eyaml`.

Add support for hiera-eyaml-gkms

---

internal/app/plan.go

This commit fixes a few places where the function name and its documentation comment do not match.
Background: I'm doing a research study on function comments that may be improvable. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
 
Thanks for reviewing!

Fix small mistakes in function doc comments

---

Dockerfile

I found issue when encrypting/decrypting secrets with hiera-eyaml using GKMS in docker container. eyaml fails with error message:
```
Error loading shared library ld-linux-x86-64.so.2
```
Issue resolved by adding `gcompat` package.

Fix issue with hiera-eyaml-gkms encrypt/decrypt actions

---

README.md

Update installation commands to use the latest version. Version 3.11.0 does not work anymore with the latest versions of kubectl due to the deprecation of the `--short` flag on `kubectl version`.
Maybe this can be automated in the future using a GitHub action?

Update README.md v3.17.0

---

internal/app/cli.go
internal/app/release.go

Add the ability to show secrets when diffing, via `--show-secrets`. Default to off of course

feat: add show-secrets option

---

internal/gcs/gcs.go

fix segfault on gcp metadata server check

---

internal/app/kube_helpers.go
internal/app/main.go

Proposal to address issue described in: https://github.com/Praqma/helmsman/issues/934

Create namespace with labels & annotations in a single request

---

docs/cmd_reference.md
internal/app/cli.go
internal/app/release.go

Summary
This pull request reintroduces the `--verify` flag functionality to the Helmsman project. The `--verify` flag enables verification of downloaded charts during install/update operations. The implementation has been rewritten for improved simplicity and reliability.
When the `--verify` flag is set:
- A provenance file must be present for each chart.
- The provenance file must successfully pass all verification checks.
Related PRs: #953, #946 
cc: @rvbcia

feat: Add option to verify charts before using them
