decision_maker.go
decision_maker_test.go
docs/deplyment_strategies.md
docs/desired_state_specification.md
docs/how_to/multiple_value_files.md
release.go
release_test.go

multiple yaml value files

---

README.md
main.go

Looks like there were some missed spots when 1.2.0 came out. I think I captured all of them.

Updating to 1.2.0 final release.

---

README.md
dockerfile/README.md
dockerfile/dockerfile
docs/deplyment_strategies.md
docs/desired_state_specification.md
docs/how_to/define_namespaces.md
docs/how_to/manipulate_apps.md
docs/how_to/move_charts_across_namespaces.md
docs/how_to/multiple_value_files.md
docs/how_to/multitenant_clusters_guide.md
docs/how_to/override_defined_namespaces.md
docs/how_to/pass_secrets_from_env_variables.md
docs/how_to/protect_namespaces_and_releases.md
docs/how_to/run_helmsman_with_hosted_cluster.md
docs/how_to/run_helmsman_with_minikube.md
docs/how_to/test_charts.md
docs/how_to/use_local_charts.md
docs/how_to/use_private_helm_charts.md
example.yaml
init.go
release.go
state.go
test_files/invalid_example.yaml
utils.go
utils_test.go

support for yaml files

---

test_files/dockerfile

This should fix the issues caused by #74.
Sorry for overlooking that.

don't run as root

---

decision_maker.go
dockerfile/dockerfile
docs/desired_state_specification.md
helm_helpers.go
main.go
release.go

Adding support for the helm-secrets plugin

---

helm_helpers.go
helm_helpers_test.go

Fixes chart version that are valid semantic version strings.

---

decision_maker.go

This addresses #78 (In addition to other commits which also address it)

Fixed one more place where we need to single quote a version.

---

helm_helpers.go
init.go
main.go

adding flag to disable namespace creation

---

kube_helpers.go

delete untracked releases

---

docs/desired_state_specification.md
example.toml
example.yaml

fixes #123

---

utils.go

adding file path resolution for certificates

---

helm_helpers.go

This should solve the problem reported in #139

fixes #139

---

release.go
utils.go
utils_test.go

allowing yaml and yml files. fixes #141

---

docs/deployment_strategies.md
docs/how_to/override_defined_namespaces.md
docs/how_to/use_the_priority_key.md
docs/why_helmsman.md

This fixes a number of spelling issues in docs, as well as one markdown filename.

Fix spelling issues in docs

---

README.md
command.go
docs/desired_state_specification.md
docs/how_to/define_namespaces.md
example.toml
example.yaml
kube_helpers.go
namespace.go
release.go
release_test.go
state.go
state_test.go
utils.go

Read more about `LimitRange`s in:
- https://docs.openshift.com/enterprise/3.2/dev_guide/compute_resources.html#dev-viewing-limit-ranges
- https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/
- https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/

Adding a way to define a LimitRange per namespace

---

decision_maker.go
docs/desired_state_specification.md
helm_helpers.go
release.go

allow setting helm flags in the DSF

---

docs/cmd_reference.md
docs/how_to/use_local_charts.md
init.go
kube_helpers.go
main.go
state.go

This should fix #153 @bergerx could you test it in your use case?

make settings.kubeContext optional and respect current context

---

dockerfile/dockerfile
test_files/dockerfile

Made some additional changes to bring the test and final docker files closer to each other.

 sync dockerfiles, fix #157, fix #156

---

decision_maker.go
docs/how_to/manipulate_apps.md

fix(logging): Fix typo "planing" to "planning" in log statements

---

release.go
release_test.go

adding validation for apps Set env vars. Fixes #149

---

docs/desired_state_specification.md
example.toml
example.yaml
helm_helpers.go
kube_helpers.go
namespace.go
release_test.go
state_test.go

Addressing Issue https://github.com/Praqma/helmsman/issues/180

Adding support to specify the tiller role.

---

docs/desired_state_specification.md

Just making the desired spec docs look a little more nicer.

Minor document formatting fixes

---

init.go

Ensure version is printed before processing any input files

---

helm_helpers.go
kube_helpers.go
main.go
state.go
state_test.go
utils.go

allowing helmsman to connect to the cluster using a bearer token and updating relevant validations and tests.

allowing cluster connection with bearer token. Fixes #167 #197 #203

---

example.toml
example.yaml
helm_helpers.go
main.go
state.go
state_test.go
utils.go

this also makes the `helmRepos` stanza optional in the desired state file.

support basic auth for helm repos. fixes #211

---

decision_maker.go

Showing diff when only chart version is changed

Adding diff for chart version upgrade

---

decision_maker.go

Looks like logic for cleaning up secrets is already present, but previously it was skipped.

Cleanup helms secrets if any

---

helm_helpers.go
main.go
utils.go

this replicates behaviour in #121 to fix #226

substitute env vars in values files. fixes #226

---

decision_maker.go

fixes https://github.com/Praqma/helmsman/issues/250

add helm flags to "helm diff upgrade ..." command

---

decision_maker.go

Remove getHelmFlags from diff, add to install/upgrade/delete release func

---

main.go
plan.go

I wanted to add some visibility to plan's steps apply, so we all know what chart is currently being applied.

Add start & finish apply messages for each chart

---

helm_helpers.go
main.go

fix helm init happens before overriding stable repo fixes #245

---

docs/desired_state_specification.md
helm_helpers.go
namespace.go
release_test.go
state_test.go

This resolves #277 request done by @RothAndrew

Add --history-max Tiller's parameter support

---

docs/best_practice.md
docs/cmd_reference.md
docs/deployment_strategies.md
docs/desired_state_specification.md
docs/how_to/README.md
docs/why_helmsman.md

* re-sequeced items in cmd_reference.md to make them alphabetical.

Fixes to grammar and sequencing of text

---

docs/desired_state_specification.md

Show how to use setString with nested yaml key

doc: add setString usage example

---

helm_helpers.go

This commit allows helmsman to work properly with one Tiller managing hundreds of releases. Unfortunately paging is not possible for output in text format because there is no information if next page is available. Fixes #227

Add paging for helm list with JSON output

---

CONTRIBUTION.md

typo: changed 'featuer' to feature

---

docs/cmd_reference.md
init.go
main.go
utils.go

Original feature request: github.com/Praqma/helmsman/issues/301
Follows existing config conventions, tested manually.

adding flag to opt out of default Helm repos automatic set

---

helm_helpers.go

Error message with merged path and version makes confusion and looks like helmsman is looking for chart in wrong path.

clarify error message

---

dockerfile/dockerfile

Add dep ensure to Dockerfile

---

decision_maker.go
decision_maker_test.go
helm_helpers.go
helm_helpers_test.go
plan.go
test_files/chart-test/Chart.yaml
utils.go

Better local chart handling + logging cleanup.
Fixes #310

Local chart usage fix

---

.circleci/config.yml
Makefile
bindata.go
decision_maker.go
decision_maker_test.go
dockerfile/dockerfile
helm_helpers_test.go
init_test.go
namespace.go
state_test.go
test_files/dockerfile
utils.go

Tests were failing for me after upgrading to the latest version of go, this fixes them.

fix tests for go 1.13

---

helm_helpers.go

Fix ignoring table headers when getting releases version in tillerless

---

internal/app/cli.go
internal/app/helm_helpers.go

Add a check to gracefully fail if helm 2 or older is used.

add a check for the allowed helm versions

---

internal/app/cli.go
internal/app/cli_test.go
internal/app/command.go
internal/app/decision_maker.go
internal/app/helm_helpers.go
internal/app/helm_release.go
internal/app/kube_helpers.go
internal/app/main.go
internal/app/namespace.go
internal/app/plan.go
internal/app/release.go
internal/app/release_test.go
internal/app/state.go
internal/app/utils.go

Another round of cleaning

---

internal/app/kube_helpers.go
internal/app/plan.go
internal/app/release.go
internal/app/release_test.go

label releases regardless of the helm command result

---

docs/cmd_reference.md
docs/how_to/helm_repos/default.md
examples/example.toml
examples/example.yaml
internal/app/cli.go
internal/app/main.go
internal/app/release.go
internal/app/utils.go
release-notes.md

stop adding stable helm repos by default

---

internal/app/decision_maker.go
internal/app/helm_release.go
internal/app/main.go
internal/app/release.go

This should fix #368 .
@epierotto can you test a build from this branch?
Thanks.

don't use --all-namespaces to find helm releases

---

internal/app/decision_maker.go
internal/app/release.go

Remove --purge from reInstall function

---

internal/app/release.go

Closes #396 
Signed-off-by: Moritz Schmitz von Hülst <msc@marketlogicsoftware.com>

filter returned charts for actual required chart

---

internal/app/helm_helpers.go

I'd like to limit little time consuming actions when helm repositories are added even though same are already defined.

Get existing helm repos before adding those from DSF in order to limit actions to take

---

internal/app/decision_maker.go
internal/app/helm_release.go

This may be specially useful on CI, when some jobs may cause racing condition

Make decide exiting on pending-upgrade chart state

---

internal/app/cli.go
internal/app/main.go

add --no-cleanup flag to optionally keep k8s credentials on host

---

docs/cmd_reference.md
docs/how_to/README.md
docs/how_to/apps/override_context_from_cmd.md
internal/app/cli.go

document --context-override fixes #418

---

internal/app/kube_helpers.go
internal/app/utils.go

Fix #426: race condition when creating multiple namespace limit ranges 

---

docs/cmd_reference.md
internal/app/cli.go
internal/app/decision_maker.go
internal/app/plan.go

feat: Parallelise releases with the same priority

---

.circleci/config.yml
Makefile

relates to: https://github.com/Praqma/helmsman/pull/430

fix: 1.x release job

---

internal/app/plan.go

Fix issue when nil is passed to execCommand for deletion of an untracked release

---

internal/app/cli.go
internal/app/helm_helpers.go

Fixes #513 
Adds --force-update flag if helm version >= 3.3.2

Add --force-update to helm repo add command (breaking change in 3.3.2 helm)

---

internal/app/release.go

I had various cases like:
`[2020-10-02T03:58:06.133Z] 2020-10-02 03:58:04 NOTICE: Running tests for release [ XXXX ] in namespace [ XXX ]
[2020-10-02T03:58:06.133Z] 2020-10-02 03:58:04 NOTICE: Upgrade release [ XXXX ] to version [ 1.2.0 ] in namespace [ XXX ]` causing helm tests to be run together with the release they are about to test as parallel flag was set to something > 1.
As tests are usually to verify what was deployed, I'd like to propose to run them as a last afterCommand reusing the scheme from hooks.

Run helm tests as a last command of after commands from hooks

---

internal/app/plan.go

Run release labeling as defer before release exec

---

go.mod
go.sum
internal/app/cli.go
internal/app/decision_maker.go
internal/app/helm_helpers.go
internal/app/helm_helpers_test.go

This should fix: #502 and #538

fix: no special logic for rename is needed using helm v3

---

internal/app/cli.go
internal/app/state.go

Fixes #550 
It should go as 3.6.1 asap imho

Initialize namespaces defined without any properties on init

---

examples/minimal-example.toml
examples/minimal-example.yaml
internal/app/cli.go
internal/app/cli_test.go
internal/app/command_test.go
internal/app/kube_helpers.go
internal/app/main.go
internal/app/namespace.go
internal/app/state.go
internal/app/utils.go

More tests can be added but this is a starting point

test: add test cases for readState

---

internal/app/decision_maker.go
internal/app/release.go

fix: --show-diff missing on chart version bump

---

internal/app/plan.go

Should fix #565 
I can't remember why there was such if statement on the beginning of releaseWithHooks function so I'll wait for review.
I've just wrapped before and after hooks parts in IF statement so the main cmdExec can be invoked even if targetRelease is nil (like for removing untracked release)

Accept nil targetRelease on executing command, just omit hooks part

---

Dockerfile
internal/app/cli.go
internal/app/decision_maker.go
internal/app/helm_release.go
internal/app/helm_time.go
internal/app/hooks.go
internal/app/kube_helpers.go
internal/app/plan.go
internal/app/release.go
internal/app/release_test.go
internal/app/state.go
internal/app/state_files.go
internal/app/state_files_test.go
internal/app/state_test.go
internal/app/utils.go
internal/aws/aws.go
internal/azure/azblob.go
internal/gcs/gcs.go
scripts/setup.sh

To help with the review I've created separate commits for:
* Fixing the hook annotations in the helm release
* Passing down the `debug` flag to helm
* Running the code through `gofumpt`
* Adding retries when using `curl`; sometimes the tests were failing because of that
* Improving error logging for file validation; hopefully it will help track down #567 
ps: We need a better way of asserting error types than comparing strings in our tests....

Small fixes

---

internal/app/release_files.go
internal/app/state_files.go

fix: lifecycle hook file paths not being resolved

---

docs/desired_state_specification.md
docs/how_to/README.md
docs/how_to/misc/send_ms_teams_notifications_from_helmsman.md
internal/app/logging.go
internal/app/main.go
internal/app/plan.go
internal/app/state.go
internal/app/utils.go

Helmsman will send the notification to the Microsoft Teams channel. Users need to provide the MS Teams incoming connector and information to be sent in the notification.
* It is my first PR. Any suggestion is most welcome.

MS teams notification

---

internal/app/kube_helpers.go

fix: race condition when applying namespace quotas

---

internal/app/cli.go
internal/app/helm_helpers.go

feat: add flag to skip helm repo update

---

internal/app/state.go

fix: dont expect a username and password if the caClient cert is present

---

Dockerfile
Makefile
docs/how_to/apps/secrets.md
scripts/setup.sh

Helm plugin is currently maintained here: https://github.com/jkroepke/helm-secrets

replace deprecated helm-secrets repo

---

internal/app/command.go
internal/app/command_test.go
internal/app/decision_maker.go
internal/app/helm_helpers.go
internal/app/helm_release.go
internal/app/kube_helpers.go
internal/app/plan.go
internal/app/release.go
internal/app/release_files.go
internal/app/state.go
internal/app/state_test.go
internal/app/utils.go

feat: better error handling for command.Exec()

---

docs/how_to/helm_repos/README.md
docs/how_to/helm_repos/oci.md
internal/app/helm_helpers.go
internal/app/state_files.go
internal/app/utils.go

feat: support oci charts

---

docs/cmd_reference.md
internal/app/cli.go
internal/app/command.go
internal/app/command_test.go
internal/app/release.go

feat: allow using kubectl diff instead of helm diff

---

internal/app/helm_helpers.go
internal/app/utils.go
internal/app/utils_test.go

For details see:
* https://github.com/helm/helm/releases/tag/v3.7.0
* https://github.com/helm/community/blob/main/hips/hip-0006.md

feat: support the new OCI implementation from helm 3.7.0

---

Makefile
examples/composition/README.md
examples/composition/argo.yaml
examples/composition/artifactory.yaml
examples/composition/main.yaml
examples/composition/spec.yaml
internal/app/cli.go
internal/app/state_files.go
internal/app/state_files_test.go

Just some refactoring and adding more tests.
Each commit can be reviewed separately.

State composition

---

docs/desired_state_specification.md
internal/app/cli.go
internal/app/command.go
internal/app/decision_maker.go
internal/app/decision_maker_test.go
internal/app/state.go

Allow ignoring apps in pending states or try to wait for the state to change.

Pending states

---

.circleci/config.yml
Dockerfile

I'm updating go, alpine, helm plugins and helm version itself, then preparing circleci helm versions for the release.

Update helm, helm plugins, alpine and golang versions

---

go.mod
go.sum
internal/app/utils.go

fix: replace godotenv with gotenv

---

examples/composition/argo.yaml
examples/composition/artifactory.yaml
examples/composition/kyverno.yaml
examples/composition/main.yaml
examples/composition/spec.yaml
internal/app/spec_state.go
internal/app/spec_state_test.go
internal/app/state_files.go
internal/app/state_files_test.go

Alternative implementation for #669 
I've also modified the tests to make sure this case is covered.
cc: @bergerx

fix: check charts in all previous helmRepos

---

Makefile
go.mod
go.sum
internal/app/cli.go
internal/app/cli_test.go
internal/app/decision_maker.go
internal/app/decision_maker_test.go
internal/app/helm_helpers.go
internal/app/helm_helpers_test.go
internal/app/helm_release.go
internal/app/kube_helpers.go
internal/app/main.go
internal/app/namespace.go
internal/app/plan.go
internal/app/plan_test.go
internal/app/release.go
internal/app/release_files.go
internal/app/release_test.go
internal/app/state.go
internal/app/state_files.go
internal/app/state_files_test.go
internal/app/state_test.go
internal/app/utils.go
internal/app/utils_test.go
schema.go
schema.json

Adds a json schema generator for the desired state definition.
Sorry for the large PR, I had to export our types and add comments to their fields to get a meaningful `jsonschema` file being generated.
Fixes: #576

Json schema

---

internal/app/state.go
internal/app/state_test.go

Make -target consistent with app release name

---

internal/app/kube_helpers.go

I'm updating the `getKubectlVersion` function unmarshall json output of `kubectl version` instead of parsing string output. I've checked if this is supported for the command back to v1.21 of kubectl - it is.
Should fix #687

Get kubectl version by taking json output instead of parsing string

---

cmd/helmsman/main.go
internal/app/main.go

Fix broken .helmsman-tmp cleanup caused by os.Exit not respectng cleanup defer

---

docs/desired_state_specification.md
internal/app/release_files.go
internal/app/state.go
internal/app/utils.go
schema.json

This PR adds support for the [helm-vault plugin](https://github.com/Just-Insane/helm-vault) and allows most of the options to be specified as you'd expect.
I haven't written any tests that cover this behaviour, as I'm not really sure how to go about mocking something like vault in this context. If you have any ideas I'd be happy to update the PR.

Add support for helm-vault plugin

---

internal/app/helm_helpers.go
internal/app/utils.go

This should fix #715 by checking the hem secrets plugin version and adjusting the command args.

fix: check helm plugin version

---

internal/app/spec_state.go
internal/app/state_files.go

fix: allow YAML anchors

---

internal/app/utils.go

refactor: simplify the decryptSecret code

---

internal/app/utils.go

Resolved conflicts from previous PR.
Adding additional property required for hiera-eyaml-gkms

Add additional property required to use hiera-eyaml-gkms

---

docs/cmd_reference.md
go.mod
internal/app/cli.go
internal/app/cli_test.go
internal/app/helm_helpers.go
internal/app/main.go

Reverts mkubaczyk/helmsman#946

Revert "Add --verify Flag Functionality and Tests"
